Script started on 2022-02-10 11:51:19-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]0;hh35@gold17: ~/cs214/lab/lab05/clojure[01;32mhh35@gold17[00m:[01;34m~/cs214/lab/lab05/clojure[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> ^V[K(+ 1 2 3 4 5)user=> (+ 1 2 3 4 5)user=> [K(+ 1 2 3 4 5)
15
user=> [Kuser=> [Kuser=> 
[K]0;hh35@gold17: ~/cs214/lab/lab05/clojure[01;32mhh35@gold17[00m:[01;34m~/cs214/lab/lab05/clojure[00m$ exit

Script done on 2022-02-10 11:51:50-05:00 [COMMAND_EXIT_CODE="0"]
