Script started on 2022-02-10 12:12:38-05:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="80" LINES="24"]
]0;hh35@gold18: ~/cs214/lab/lab05/clojure[01;32mhh35@gold18[00m:[01;34m~/cs214/lab/lab05/clojure[00m$ ((fn    clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> ((fn px y z]       [x y z][x y z] (+ x y z)(+ x y z))user=> ((fn [x y z] (+ x y z)) 2 5 6)user=> ((fn [x y z] (+ x y z)) 2 5 6)user=> [K((fn [x y z] (+ x y z)) 2 5 6)
[K13
user=> [Kuser=> [Kuser=> ((fn [x][x] (nil? x)(nil? x))user=> ((fn [x] (nil? x)) nil)user=> ((fn [x] (nil? x)) nil)user=> [K((fn [x] (nil? x)) nil)
true
user=> [Kuser=> [Kuser=> ((fn [][] 17/2)user=> ((fn [] 17/2))user=> ((fn [] 17/2)) )user=> [K((fn [] 17/2) )
17/2
user=> [Kuser=> [Kuser=> ((fn [][] 17.2)user=> ((fn [] 17.2) )user=> ((fn [] 17.2) )user=> [K((fn [] 17.2) )
17.2
user=> [Kuser=> [Kuser=> 
[K]0;hh35@gold18: ~/cs214/lab/lab05/clojure[01;32mhh35@gold18[00m:[01;34m~/cs214/lab/lab05/clojure[00m$ exit

Script done on 2022-02-10 12:13:39-05:00 [COMMAND_EXIT_CODE="0"]
