Script started on 2022-02-10 12:41:45-05:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="80" LINES="24"]
]0;hh35@gold18: ~/cs214/lab/lab05/clojure[01;32mhh35@gold18[00m:[01;34m~/cs214/lab/lab05/clojure[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> (defn negate [sequence][sequence] (n map (fn [x][x] (* = -1 x)(* -1 x)  ()()  )(fn [x] (* -1 x)) sequence)(map (fn [x] (* -1 x)) sequence))user=> (defn negate [sequence] (map (fn [x] (* -1 x)) sequence))user=> [K(defn negate [sequence] (map (fn [x] (* -1 x)) sequence))
[K#'user/negate
user=> [Kuser=> [Kuser=> (defn negate [sequence] (map (fn [x] (* -1 x)) sequence))user=> [K(negate [-1 2 -3][-1 2 -3])user=> (negate [-1 2 -3])user=> [K(negate [-1 2 -3])
(1 -2 3)
user=> [Kuser=> [Kuser=> (negate [-1 2 -3])3[1P[1P[1P[1P[1P[1P[1P[1@4[1@ [1@-[1@5[1@ [1@6user=> [K(negate [4 -5 6])
(-4 5 -6)
user=> [Kuser=> [Kuser=> 
[K]0;hh35@gold18: ~/cs214/lab/lab05/clojure[01;32mhh35@gold18[00m:[01;34m~/cs214/lab/lab05/clojure[00m$ exit

Script done on 2022-02-10 12:42:41-05:00 [COMMAND_EXIT_CODE="0"]
