Script started on 2022-02-10 12:51:32-05:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="80" LINES="24"]
]0;hh35@gold18: ~/cs214/lab/lab05/clojure[01;32mhh35@gold18[00m:[01;34m~/cs214/lab/lab05/clojure[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> (defn sumSquares [sequence][sequence] (recue     duce + map   (am  map * sequence sequence)(map * sequence sequence))(reduce + (map * sequence sequence)))user=> (defn sumSquares [sequence] (reduce + (map * sequence sequence)))user=> [K(defn sumSquares [sequence] (reduce + (map * sequence sequence)))
[K#'user/sumSquares
user=> [Kuser=> [Kuser=> (sumSquares 1 '(12  2 3)(1 2 3))user=> [K(sumSquares '(1 2 3))
14
user=> [Kuser=> [Kuser=> (sumSquares '(1 2 3 4 5)(1 2 3 4 5)))user=> [K(sumSquares '(1 2 3 4 5))
55
user=> [Kuser=> [Kuser=> (sumSquares [-1 -2 -3 0 1)user=> (sumSquares [-1 -2 -3 0 1) ][-1 -2 -3 0 1])user=> (sumSquares [-1 -2 -3 0 1])user=> [K(sumSquares [-1 -2 -3 0 1])
15
user=> [Kuser=> [Kuser=> 
[K]0;hh35@gold18: ~/cs214/lab/lab05/clojure[01;32mhh35@gold18[00m:[01;34m~/cs214/lab/lab05/clojure[00m$ exit

Script done on 2022-02-10 12:57:01-05:00 [COMMAND_EXIT_CODE="0"]
